services:
- type: web
  name: telegram-stock-bot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python bot.py
  envVars:
    - key: TELEGRAM_BOT_TOKEN
      fromDatabase:
        name: telegram-bot-env
        property: TELEGRAM_BOT_TOKEN
    - key: ALPHA_VANTAGE_API_KEY
      fromDatabase:
        name: telegram-bot-env
        property: ALPHA_VANTAGE_API_KEY
    - key: CACHE_DURATION_STOCKS
      value: 1800
    - key: CACHE_DURATION_CRYPTO
      value: 60
    - key: ALERT_CHECK_INTERVAL
      value: 60
  regions:
    - singapore
  plan: free
  healthCheckPath: /webhook
  autoDeploy: true